name: sim_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  # common libs
  - tqdm
  - numpy
  - scipy
  - pandas
  - argparse
  - matplotlib
  # graphic libs
  - pyvista
  - pyquaternion
  # sims
  - mujoco
  - pygame
  - robot_descriptions
  # pip
  - pip
  - pip:
    - mink
